Document: graph-tool
Title: Debian graph-tool Manual
Author: <insert document author here>
Abstract: This manual describes what graph-tool is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/graph-tool/graph-tool.sgml.gz

Format: postscript
Files: /usr/share/doc/graph-tool/graph-tool.ps.gz

Format: text
Files: /usr/share/doc/graph-tool/graph-tool.text.gz

Format: HTML
Index: /usr/share/doc/graph-tool/html/index.html
Files: /usr/share/doc/graph-tool/html/*.html
